### ISSUE TITLE
t/30proclet/01_basic.t doesn't kills child process

### ISSUE THREAD

**Issue by tokuhirom** [kazeburo/Proclet#2]
after run t/30proclet/01_basic.t, following processes are remains.

1000      1061  0.0  0.0  17012  1576 pts/79   S    09:04   0:00 perl -e while(1){ open(my $fh, ">>:unix", $ENV{PROCLET_TESTFILE}) or die $!; print $fh "w2 $$\n"; close $fh; sleep 1}

And it can creates big file. I got a 31MB file in my /tmp/ directory.

Note: You should not use infinite loop in test case. Limit the loop count like `for (1..10000) { ... }` is even better.

**Comment by kazeburo** [comment]
Thanks. 
That problem was fixed in version 0.16
